### ISSUE TITLE
TidyTemplate

### ISSUE THREAD

**Issue by thebioengineer** [thebioengineer/tidytuesdayR#39]
## TidyTemplates

Provide a template that can be used with `new Rmd` to create the framework for data analysis/visualization.
## Motivation:
Some people that are new to R might not be sure where to start. IE: https://twitter.com/scottjdavies01/status/1198923622993166336

If we can provide them with a good recipe for starting, we can promote confidence and get people excited about their first analysis. 

## TidyTemplates
 - data wrangling
 - data visualization
 - data modeling

**Comment by davidski** [comment]
Referencing https://twitter.com/dseverski/status/1281604161922990080, while this was very much 😜 in spirit, there's a legitimate point that having new users work with `html_notebook` as their default experience (which is what RStudio's out-of-the-box new Rmd template promotes) is a better starting point. The auto generation on save, embedding of code, and avoiding having to manually knit are nice defaults. Not a universal opinion, to be sure, but one that is fairly safe for new Tidy Tuesday participants, I hope!

**Comment by delabj** [comment]
Would it be worth creating an argument/global option for the output type? I'm partial to `github_document()` as many users already post  their code/folder to a github repo?

Obviously, a user can adjust the result by editing the output type.

**Comment by thebioengineer** [comment]
per difficulty [here](https://www.youtube.com/watch?v=E2amEz_upzU&feature=youtu.be) in @dgrtwo's screencast- when a file exists already, see if we can open the file rather than just silently doing nothing.

**Comment by jenrichmond** [comment]
i've just discovered the tidy template and it is a great way to get beginners going with Tidy Tuesday- thanks! I am having an issue with knitting though. To get the document to knit, I need to change the output from html_output to html_document. I must be doing something wrong?? thanks, Jen


![Screen Shot 2021-09-07 at 2 56 30 pm](https://user-images.githubusercontent.com/40267093/132286623-b341329f-45dd-472d-8d83-f04fe307b6bf.png)

**Comment by delabj** [comment]
@jenrichmond I think this is correct. 

I would maybe submit this as a seperate issue, but it looks like pull request #80 has this fix, so we'd just need that to get merged.
