### ISSUE TITLE
TidyTuesday has only existed from 2018 to 2019

### ISSUE THREAD

**Issue by randy-tarnowski** [thebioengineer/tidytuesdayR#40]
Unable to load most recent dataset for TidyTuesday.
`
tuesdata <- tidytuesdayR::tt_load('2020-01-07') 
`

**Comment by thebioengineer** [comment]
Thanks for the submission. I was wondering and hadn't had a chance to check. It should be resolved now. 

This shows I need to look into using the underlying github API rather than the website.

**Comment by randy-tarnowski** [comment]
Awesome! Additionally, the package is misaligned with the TidyTuesday week count (e.g. Australia Fires is listed as week 2, but forced to request week 1 in the function (tuesdata <- tidytuesdayR::tt_load(2020, week = 1))

**Comment by thebioengineer** [comment]
Yes, I am working on correcting that now too. It is due to there only being a single file in the 2020 data folder at the moment

**Comment by thebioengineer** [comment]
I believe this issue has been resolved. Thanks for your submission!
