### ISSUE TITLE
Download by week failing for 2020

### ISSUE THREAD

**Issue by jonthegeek** [thebioengineer/tidytuesdayR#42]
``
> tuesdata <- tidytuesdayR::tt_load(2020, week = 4)
Error in tt_make_url.year(x, week) : 
  Only 2 TidyTuesday Weeks exist in 2020. Please enter a value for week between 1 and 2
```

I tried using both the master and dev, and got the same error.

`tuesdata <- tidytuesdayR::tt_load('2020-01-21')` works on both.

**Comment by thebioengineer** [comment]
Interesting. Thanks!

**Comment by thebioengineer** [comment]
The issue has to do with relying on the readme in the data/2020 folder not being updated. I am submitting a PR to @jthomasmock now

**Comment by thebioengineer** [comment]
pull request is open: https://github.com/rfordatascience/tidytuesday/pull/166

**Comment by thebioengineer** [comment]
Should be resolved now. Let me know if it isn't and we can reopen this!
