### ISSUE TITLE
Versioning Suggests/Dependencies

### ISSUE THREAD

**Issue by jthomasmock** [thebioengineer/tidytuesdayR#5]
I needed to install all the dependencies to most recent version to install the package:

I assume that vast majority of newer TidyTuesday people are not using the most recent version of all the packages, so it might be a good idea to either set the minimum back a few versions or otherwise improve that situation.

**Comment by thebioengineer** [comment]
Is this the prompt from devtools::install_github? You don't need to do that, just make sure you are at the same version that the package requests

**Comment by jonthegeek** [comment]
I started to write each of these as a separate issue, but that might be taking it too far. I'm not sure what it takes to install old versions of packages, but I know it's possible, and I think it's worth doing for this one.

**Comment by thebioengineer** [comment]
Thinking back on this, I think we can probably not have versions on those packages that you specified, as the functionality I am using are core to the packages and thus not really necessary.

**Comment by thebioengineer** [comment]
@jonthegeek try installing from the dev branch and see if that works for you

**Comment by jonthegeek** [comment]
It isn't that I'm having trouble installing; it's that, since this is a package aimed largely at R beginners, I think it'd be good for us to figure out and specify the actual minimum version needed, so install.packages will update those packages if and only if they need to be updated.

**Comment by jthomasmock** [comment]
I think this could be helpful and solve the issue:
> Imports:
    ggvis (>= 0.2),
    dplyr (>= 0.3.0.1)
Suggests:
    MASS (>= 7.3.0)

Could also do` '#@importFrom` if you only need a small function from one of the big packages

**Comment by jonthegeek** [comment]
Yeah, we still need to mention it in Imports even if w use importFrom. What I'm looking to sort out is the *minimum* version of each that we actually require, to minimize pain for users.

**Comment by thebioengineer** [comment]
Do you know of a method of 'back-porting' essentially to go back and check? or is it manual?

From what I am understanding is that we want to ensure that the users will be able to install this package, and just have it work?

**Comment by jonthegeek** [comment]
@thebioengineer I'm not sure, but I'm PRETTY sure that's possible. I'm hoping to invest some time in learning how to do that this weekend. I never bother for my packages at work, because it's easy enough for us all to just update to the latest... but it seems worthwhile to me to make this as painless as it possibly can be.

**Comment by thebioengineer** [comment]
@jonthegeek I thought by not enforcing a version of the package, it would just check that the package is installed, and not force an update? The install_github is the one that checks for updates and offers to update, but if I can get this onto the cran, it won't do that.

I am also in the same boat- used to internal uses where updating wasn't a big deal nor did I care if I forced a coworker to update

**Comment by jonthegeek** [comment]
@thebioengineer I think technically we COULD just leave the version off... but, in the case where an old version doesn't work, we *do* want to force them to update (so they aren't confused why it doesn't work). It's probably overboard, but I just want to make sure everything is perfect :)

**Comment by thebioengineer** [comment]
Ahhh, now I understand your goals better. 🎉 🎉 🎉 

I am relatively certain that most of the uses of the packages I reference are core to their functionality and thus should "just work", but that is reasonable to take a look back and see if it is true

**Comment by thebioengineer** [comment]
@jonthegeek take a look at the dev branch, I just pushed an update with the minimum package version for several packages based on when the specific function appeared in a package or when specific functionality appeared.

**Comment by jonthegeek** [comment]
@thebioengineer Fantastic work! I'm hoping to devote at least a couple hours to this package tomorrow. I'll see if I can set up a test install of R with all of the minimums so we can make sure it keeps working!

**Comment by jonthegeek** [comment]
I'm working on this now... and RStudio put up a handy guide to doing pretty much exactly this three days ago! Woot! https://support.rstudio.com/hc/en-us/articles/219949047-Installing-older-versions-of-packages

**Comment by jthomasmock** [comment]
Also keep pak in mind - you can temp install versions. 

https://github.com/r-lib/pak/blob/master/README.md

**Comment by jonthegeek** [comment]
Ya know... it also might be possible to set this up via Travis, and just have it run checks on an old machine. I haven't played with Travis at all, but it looks like @thebioengineer has. Do you think this might be something to check out there? I'm thinking maybe something something config variables in the travis yaml with older versions, and we just step those versions back until it fails?

**Comment by thebioengineer** [comment]
@jonthegeek I can look into it, but im pretty sure there is. As I understand it travis is just spinning up docker containers. Admittedly my experience is just figuring out how to make it work and not much more 🤣

**Comment by thebioengineer** [comment]
@jonthegeek just pushed an updated .travis.yml that hopefully will do what we are looking for

**Comment by jonthegeek** [comment]
> @jonthegeek just pushed an updated .travis.yml that hopefully will do what we are looking for

Awesome!

I'm going through the package and applying some tidyverse-inspired styling rules (and using it to get a general feel for the code). Hopefully I'll have another PR tonight.

**Comment by thebioengineer** [comment]
@jonthegeek Thanks! I try to keep the development work on the 'dev' branch, if you could push to that one going forward. Once it passes CI, I push to the master

**Comment by jonthegeek** [comment]
Will do!

**Comment by jonthegeek** [comment]
I think we can call this good enough for now at least. I'm gonna try to finish up my cleanup, and then get the test coverage as close to 100% as we can... And then I MIGHT put a package together to test minimum package versions; I have an idea of how to make it work, and it doesn't look like such a thing exists.

**Comment by thebioengineer** [comment]
Great, let me know when you are ready. Most of the loss of code coverage is due to the lack of testing the rstudio viewer html pages that I am generating from the readme.

Also it does sound like a minimum package version finder would be of value - I am interested to see what you come up with

**Comment by thebioengineer** [comment]
@jonthegeek Do you have any updates to be merge? I was thinking of merging the dev branch with the master since it has some fixes for reading xls/xlsx files that is somewhat crucial ( Hadn't realized that readxl doesn't implement URL reading yet when i put it in)

**Comment by jonthegeek** [comment]
@thebioengineer go ahead and merge. I'll get caught up soon. This was a crazy weekend, so I didn't get as much done as I'd have liked.
