### ISSUE TITLE
V1.0.0 CRAN submission feedback

### ISSUE THREAD

**Issue by thebioengineer** [thebioengineer/tidytuesdayR#55]
- [x] Please always write non-English usage, package names, software names and API names in *undirected* single quotes in title and description in the DESCRIPTION file.

- [x] Please only capitalize names, sentence beginnings andabbreviations/acronyms in the description text of your DESCRIPTION file.

- [x] Please add () behind all function names in the description text in the DESCRIPTION file. Please don't quote them. e.g. `tt_load` --> tt_load()

- [x] Please add a web reference for this project in your Description field of the DESCRIPTION file in the form <http:...> or <[https:...]https:...> with angle brackets for auto-linking and no space after 'http:' and 'https:'.

- [x] Unexecutable code in man/tt_load_gh.Rd:
    - unexpected symbol: readme (Possibly missing parentheses?)

- [x] Please add \value to .Rd files regarding exported methods and explain the functions results in the documentation. Please write about the structure of the output (class) and also what the output means. (If a function does not return a value, please document that too, e.g. \value{No return value, called for side effects} or similar)

- [x] You have examples for unexported functions which cannot run in this way. Please either omit these examples or export these functions.

- [x] \dontrun{} should be only used if the example really cannot be executed (e.g. because of missing additional software, missing API keys, ...) by the user. That's why wrapping examples in \dontrun{} adds the comment ("# Not run:") as a warning for the user. Please unwrap the examples if they are executable in < 5 sec, or create additionally small toy examples to allow automatic testing. Please also add small executable examples in your Rd-files where you don't have examples yet to illustrate the use of the exported functions but also enable automatic testing. When creating the examples please keep in mind that the structure would be desirable:
```r
\examples{
    examples for users and checks:
    executable in < 5 sec
    \dontshow{
        examples for checks:
        executable in < 5 sec together with the examples above
        not shown to users
    }
    \donttest{
        further examples for users; not used for checks
        (f.i. data loading examples, or time consuming functions )
    }
    \dontrun{
     not used by checks, not used by example()
     adds the comment ("# Not run:") as a warning for the user.
     cannot run (e.g. because of missing additional software,
     missing API keys, ...)
    }
    if(interactive()){
        functions not intended for use in scripts,
        or are supposed to only run interactively
        (f.i. shiny)
    }
}
```
Your users will appreciate to see how the function is supposed to be
called for tiny examples.

**Comment by thebioengineer** [comment]
@jonthegeek @jthomasmock - pushed my updates to the CRAN-edits-v1 branch and doing the requisite checks on rhub. win-devel, etc.

If you wouldn't mind giving a quick look to see if you agree that I've met the CRAN feedback, that would be great!

**Comment by thebioengineer** [comment]
Issues with 'calibre' detritus begin generated on CRANs build servers is causing failure. Requested this note to be ignored. Response:


This are files genereted if you start some web browser.
So the files are not directly your fault, but it shows yet another
problem: You should not start a web browser in  non interactive mode, so
please protect such examples by

if(interactive())

**Comment by thebioengineer** [comment]
Additional feedback:

- [ ] If GitHub is not available vor any reason, your functions should return a message and not result in an error.

- [x] Examples in \donttest are not executed in our checks. Hence, using \donttest should be sufficient.

**Comment by jonthegeek** [comment]
Weird. I'd far prefer an error when the function, ya know, fails to do what it's supposed to do. I've seen (and fought against) this pattern elsewhere before, but I guess do what they say.

**Comment by thebioengineer** [comment]
Per CRAN: 

> A package must not fail for internet access matters, you have to make sure this does not happen. If a key is required, \donttest{} is certainly fine.

Not sure what that means. Will think on it.

**Comment by thebioengineer** [comment]
Alright, I thought about it, and added this things:
- an internet connectivity check .onload and periodically throughout the package.
- updated how "bad" github calls are made (unlikely to happen since the user has no control on these, but CYA 🤷 )
- in the user facing functions that require internet/API calls, now all have a check at teh beginning and will have the function return NULL with a message indicating why (no internet, no API calls left, etc)

This code is not very "pretty" anymore due to these checks, will probably need to do that in a future thing, but focused on release ATM.

Next steps:
- [ ] Currently checking build status w/ github actions
- [ ] Send to rhub for checking
- [ ] Send to win-devel for checking
- [ ] Submit to CRAN for re-review

**Comment by thebioengineer** [comment]
https://cran.r-project.org/web/packages/tidytuesdayR/index.html

🥳🥳

**Comment by thebioengineer** [comment]
Now to tag and merge the branch!

**Comment by thebioengineer** [comment]
We may be on CRAN, but apparently there is an issue with solaris? Anyone know how to debug?

https://cran.r-project.org/web/checks/check_results_tidytuesdayR.html
