### ISSUE TITLE
Issues with using {tidytuesdayR} on RStudio Cloud?

### ISSUE THREAD

**Issue by jrosen48** [thebioengineer/tidytuesdayR#65]
Hi all, I've had an issue using (the fantastic) {tidytuesdayR} package on RStudio Cloud. In short, I am running into a warning (that is indicating that no output is returned): "No Internet Connection was found". I posted on RStudio Community, but haven't heard anything back just yet: https://community.rstudio.com/t/using-tidytuesdayr-on-rstudio-cloud-no-internet-connection-was-found/74322

**Comment by jthomasmock** [comment]
I can't see that specific post for some reason!

**Comment by jrosen48** [comment]
ah I lost the last '2' at the end of the URL - thanks for checking this!

**Comment by jrosen48** [comment]
updated now

**Comment by thebioengineer** [comment]
Thanks for the comment - it looks like rstudio cloud is protecting you from my potential "bug" - on loading tidytuesdayR it does a quick check against the github API to make sure you have connectivity ability - specifically it is an internal function called `check_connectivity()`. It looks like it doesn't like my mal-formed url (that for some reason had yet to cause any other locations issues!)
 I'll push an update here first, so you can install via the remotes package

**Comment by thebioengineer** [comment]
@jrosen48 - could you install the dev branch and test it out? It now works on my rstudio cloud instance - 

`remotes::install_github("thebioengineer/tidytuesdayR@dev")`

**Comment by jrosen48** [comment]
worked like a charm!

Thank you! Excited to use this with students who are new to using R.
