### ISSUE TITLE
Error with tt_load().

### ISSUE THREAD

**Issue by bbgatch** [thebioengineer/tidytuesdayR#71]
Hello,

I just installed `tidytuesdayR` for the first time and tried running `tt_load()` and I get the following error:
```
Error in if (TT_GITHUB_ENV$RATE_REMAINING == 0 & !quiet) { : 
  argument is of length zero
```

I tried both the date string and week number:
> tt_load('2020-08-04')
> tt_load(2020, week = 32)

Let me know if I can provide other information to help solve this.

I'm not sure if I should be posting here with this issue or somewhere else, please let me know if I should post elsewhere. I tried reinstalling/updating R, RStudio, and all my existing packages and I still get the error.

Thanks,
Ben

**Comment by thebioengineer** [comment]
Hi @bbgatch - thanks for bringing this up. That's a very strange bug indeed! Apologies. This is a check to ensure we don't keep hitting against the github API when we no longer have any requests left. Could you try executing `tidytuesdayR:::rate_limit_update()` then `tidytuesdayR:::rate_limit_check()`?

**Comment by bbgatch** [comment]
Hello! Sure thing, I tried those and got another strange error and then the same error:

![image](https://user-images.githubusercontent.com/10412365/89694950-53e4d100-d8e0-11ea-8d2d-6cbb1157755b.png)

Perhaps something is messed up with my machine if I'm the only one seeing this.

**Comment by thebioengineer** [comment]
Try using three `:` for the `rate_limit update()` step. It is an internal function to the package.

```
tidytuesdayR:::rate_limit_update()
tidytuesdayR:::rate_limit_check()
```

**Comment by bbgatch** [comment]
Ahh ok cool! I've never heard of that, good to know. The `update` doesn't return anything and the `check` gives me the same error.
![image](https://user-images.githubusercontent.com/10412365/89698375-d8d6e700-d8ee-11ea-9509-efe6101dbe86.png)

**Comment by asbates** [comment]
I'm having the same issue.

If it helps, I took a quick look and it seems like it might be an authentication problem. In the`GET` call [here](https://github.com/thebioengineer/tidytuesdayR/blob/51dfba6f4c33c6410473204b7893184b5e7b2b18/R/github_api.R#L395), I get a 401 error with "Bad credentials" message. So maybe my GitHub PAT is expired or something? With the `GET` response not as expected, that leads to `TT_GITHUB_ENV$RATE_REMAINING` not getting a value.

**Comment by thebioengineer** [comment]
Thanks for sharing - I'll be sure to investigate this and have it "fail" more gracefully when the authentication fails! That is a good catch!

**Comment by asbates** [comment]
FYI, I've updated my GitHub PAT and everything is working fine now.

**Comment by thebioengineer** [comment]
Great, thanks for confirming that! I'll need to add in some code to check to see if the returned error github saying it is a malformed token, etc. but that really helps clarify the issue 👍

**Comment by Agasax** [comment]
Hi, any news on this? I'm having the same issue, updated my GItHub PAT to no avail.

**Comment by thebioengineer** [comment]
Thanks for bringing this up. The current plan is to update tidytuesdayR to rely on the gh package and offload the github api interfacing to that package. as for now, could you a) post the error b) post the results of the debugging code I posted?

**Comment by Agasax** [comment]
Yes, I'm getting the exact same as reported above:

``` r
tidytuesdayR:::rate_limit_update()
tidytuesdayR:::rate_limit_check()
#> Error in if (TT_GITHUB_ENV$RATE_REMAINING == 0 & !quiet) {: argument is of length zero
```

<sup>Created on 2021-05-24 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by thebioengineer** [comment]
Intersting. Could you try the following and post the results? This should force there to be a value

```r
tidytuesdayR:::rate_limit_update(list(limit = 5000, remaining = 60, rate_reset = "2021-05-24"))
tidytuesdayR:::rate_limit_check()
```

**Comment by Agasax** [comment]
It does:

``` r
tidytuesdayR:::rate_limit_update(list(limit = 5000, remaining = 60, rate_reset = "2021-05-24"))
tidytuesdayR:::rate_limit_check()
#> [1] 60
```

<sup>Created on 2021-05-24 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by thebioengineer** [comment]
Great. now lets see what happens when we send a query to github:

```r
val_no_auth <- tidytuesdayR:::github_contents("LICENSE", auth = NULL)
val_auth <- tidytuesdayR:::github_contents("LICENSE")
substr(val_no_auth, 0, 76)
substr(val_auth, 0, 76)
```

**Comment by Agasax** [comment]
``` r
tidytuesdayR:::rate_limit_update(list(limit = 5000, remaining = 60, rate_reset = "2021-05-24"))
tidytuesdayR:::rate_limit_check()
#> [1] 60

val_no_auth <- tidytuesdayR:::github_contents("LICENSE", auth = NULL)
val_auth <- tidytuesdayR:::github_contents("LICENSE")
#> Error in tidytuesdayR:::github_contents("LICENSE"): Response Code 401: Bad credentials
substr(val_no_auth, 0, 76)
#> [1] "Creative Commons Legal Code\n\nCC0 1.0 Universal\n\n    CREATIVE COMMONS CORPORA"
#> attr(,".sha")
#> [1] "_a_licence_nr_"
substr(val_auth, 0, 76)
#> Error in substr(val_auth, 0, 76): object 'val_auth' not found
```

**Comment by thebioengineer** [comment]
Okay, so it looks like your PAT is incorrect. Check your locally stored PAT via `tidytuesdayR:::github_pat()` against what you expect. If its not, update the githup pat in your .Renviron

**Comment by Agasax** [comment]
You are absolutely right, sorry about this. I thought it was due to a bug since it was the same error others had been getting.
Thanks for the help!
