### ISSUE TITLE
usethis failing revdep check at CRAN

### ISSUE THREAD

**Issue by jennybc** [thebioengineer/tidytuesdayR#77]
We're trying to do a patch release of usethis and tidytuesdayR failed the revdep check for them (not in our pre-checks, though). This looks like ... an intermittent internet problem to me? It seems unlikely to have anything to do with usethis. Do you concur?

https://win-builder.r-project.org/incoming_pretest/usethis_2.0.1_20210210_003949/reverseDependencies/changes.txt

Have you considered using `skip_on_cran()` for this sort of test? They often cause problems, both direct and indirect, on CRAN.

**Comment by hadley** [comment]
It looks like `check_api()` is supposed to do this but there's a bug in the logic somewhere that's leading to `Error: argument is of length zero`

**Comment by thebioengineer** [comment]
Hi @jennybc and @hadley -

Thanks for the review and notice. My dependency on {usethis} is to make it so users could access a template. Therefore I highly doubt the failure is due to {usethis}.

Yes, `check_api()` should be confirming that there are still at least N available queries available, to prevent errors in tests when the rate limit was met. This wasn't specifically to get around CRAN's issues, but I think it did end up helping me get around the intermittent internet problem. This "Argument is of length zero" issue, that is an interesting one that I will be looking at trying to replicate.

**Comment by jennybc** [comment]
usethis went through regardless, so that's good. But you might want to revise this testing strategy, so it doesn't crop up again  for tidytuesdayR or one of its dependencies. This sort of thing means the package in question can't flow through the CRAN robot.

**Comment by thebioengineer** [comment]
I will be updating for sure - I think what happened is that the 502 error created a weird bug in the logic where then it cleared out the value I used to check that the rate limit has not been met, so then it returned an NA or NULL, which caused the `argument of length zero` issue. I will be adjusting based on feedback from Hadley to use gh.

**Comment by jennybc** [comment]
Hello again. The same thing just happened again with the usethis 2.1.0 submission. It's hopefully not a huge deal, but it does keep my package from going through the robot. And every time one invites unnecessary human intervention at CRAN, it's not a great day.

I will file this away as a possible "community service" project for one of us to maybe pitch in on. I'm not promising anything, but would you be open to assistance with addressing the issues identified in this thread, #79, and #78?

If so, I'll try to see if some this refactoring might be helpful as a little concrete project when I resume work on the R Packages revision, which is what's next once I release usethis. That's a possible win-win, for both of us.

**Comment by thebioengineer** [comment]
Hi Jenny - Apologies for not getting on this. Its been a busy year and not had the bandwidth to do an overhaul needed to address everything.

I would definitely accept any help people are willing to provide. The package came out of the goal to help people, not make your life harder!!
