### ISSUE TITLE
Use the gh package?

### ISSUE THREAD

**Issue by hadley** [thebioengineer/tidytuesdayR#78]
I'd highly recommend switching to the gh package since it takes care of many detail that you'll otherwise need to do yourself. Most importantly, we're gradually moving away from storing the `GITHUB_PAT` in an environment variable, and instead storing it in a secure credential store: https://www.tidyverse.org/blog/2020/12/usethis-2-0-0/#personal-access-tokens-pats.

**Comment by thebioengineer** [comment]
Thanks for the heads up. I'll look into that more closely. I had written the functions and released the package before learning about {gh}, but with the new process it definitely makes sense to offload the work to there.
