### ISSUE TITLE
knit problem with Tidy template

### ISSUE THREAD

**Issue by jenrichmond** [thebioengineer/tidytuesdayR#84]
i've just discovered the tidy template and it is a great way to get beginners going with Tidy Tuesday- thanks! I am having an issue with knitting though. To get the document to knit, I need to change the output from html_output to html_document. 

thanks, Jen

![knit](https://user-images.githubusercontent.com/40267093/132609471-3fea2f3c-d4ac-4b37-842b-4ddecc7e5dfd.png)

**Comment by thebioengineer** [comment]
Hi @jenrichmond - thanks for bringing this up. I'll aim to get a fix out to CRAN soon!

**Comment by thebioengineer** [comment]
This is fixed in the latest CRAN release. Thanks for bring it up!
