### ISSUE TITLE
Failing CRAN check

### ISSUE THREAD

**Issue by jonthegeek** [thebioengineer/tidytuesdayR#94]
The package has an error on CRAN, and we have until 2024-08-29 to fix it: https://cran.r-project.org/web/checks/check_results_tidytuesdayR.html

It looks to me like the test might have ran when there was an issue. We can probably deal with almost all examples using [@examplesIf](https://r-pkgs.org/man.html#sec-man-examples-dependencies-conditional-execution), probably with a basic `interactive()`.

**Comment by thebioengineer** [comment]
this happens periodically, but it has been a minute now. Its randomly a connectivity issue, and it violates crans rules about "failing gracefully", but it does, just with an error saying it fails.
